---
title: "MUSA 550 Final Project Template"
subtitle: "An example website demonstrating the power of Quarto for sharing analyses on the web"
---

## Welcome!

Hello!

Welcome to this page that was made using Quarto! I am excited to share with you my final project for my Geospatial Data Science in Python course. 

Early into my Master's in Urban Spatial Analytics program in the University of Pennsylvania's School of Design, I was given the opportunity to intern with Nehemiah HDFC, an affordable housing development company based out of New York City. Nehemiah has 30+ years of experience transforming neighborhoods that were once blighted and undesirable, and in the process they have built extraordinary wealth for families that would otherwise be left out of the prosperity that can come with gentrification. Through Homeownership Nehemiah has been able to deeply impact the lives of individuals and their communities. 

The purpose of my project was to take lists of addresses that contained each property that Nehemiah has developed and merge them with NYC's cross-departmental database (MAPPLUTO)that included the polygons of the lots. In order to do this, each list had to be wrangled in a different way prior to merging with the MAPPLUTo. The project yielded a shapefile that contained all of the lot-level data, including the geometries, that NYC had to offer for each of the addresses. The final result is that Nehemiah, for the first time in its history, could visualize where their properties were on a map. The scale of their effort is remarkable and its success is worth sharing as a model for transformative change in marginalized communities. 



 
